const actionTypes = {
  ADD_BUDGET: "ADD_BUDGET",
  DELETE_BUDGET: "DELETE_BUDGET",
  ADD_EXPENSE: "ADD_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  GET_BUDGET_EXPENSES: "GET_BUDGET_EXPENSES",
  GET_BUDGET_EXPENSE_LIST: "GET_BUDGET_EXPENSE_LIST",
};

export default actionTypes;
